Add check for EPEL archive availability in Dockerfile for FLEXPART base image.

diff --git a/tests/Dockerfile b/tests/Dockerfile
--- a/tests/Dockerfile
+++ b/tests/Dockerfile
@@ -12,7 +12,8 @@ EOF
 # this fixes the correct version of the repo, even if just 9 or 8 are used.
 # allows to install older version of eccodes and netcdf
 RUN export RL_RELEASE=$(cat /etc/redhat-release | awk '{print $4}') && sed -i "s/RL_RELEASE/${RL_RELEASE}/" /etc/yum.repos.d/epel-ar.repo
-RUN export EXTRA_REPO=$((microdnf  repolist --all | grep crb 1>/dev/null) && echo crb || echo powertools) && \
+RUN curl -s --head https://archives.fedoraproject.org/pub/archive/epel/${RL_RELEASE}/Everything/\$basearch/ | grep "200 OK" || (echo "EPEL archive not found for Rocky Linux ${RL_RELEASE}" && rm -fv /etc/yum.repos.d/epel-ar.repo )
+RUN export EXTRA_REPO=$((microdnf repolist --all | grep crb 1>/dev/null) && echo crb || echo powertools) && \
 	microdnf install -y epel-release && \
 	microdnf install -y --enablerepo=${EXTRA_REPO} make netcdf-fortran-devel.x86_64 netcdf.x86_64 eccodes eccodes-devel cmake tar gcc-c++ perl git wget && \
  	microdnf clean all -y && \
